name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        run: |
          docker run --rm \
            --network host \
            -e SONAR_HOST_URL=http://127.0.0.1:9000 \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v /volume1/docker/ethical-finance:/usr/src \
            sonarsource/sonar-scanner-cli:5
