name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        run: |
          /volume1/docker/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=ethical-finance \
            -Dsonar.sources=/volume1/docker/ethical-finance/backend \
            -Dsonar.host.url=http://192.168.1.47:9000 \
            -Dsonar.token=sqa_b573b366e26e8394859948e7122360ee49752de5
