name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        run: |
          /volume1/docker/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=ethical-finance \
            -Dsonar.sources=/volume1/docker/ethical-finance/backend \
            -Dsonar.host.url=http://127.0.0.1:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
